version: "3.5"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass

  www:
    image: php:8.1-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80
      - 443:443

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: pass