version: "3.5"

services:
  php:
    image: php:8.1-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80

  db:
    image: mysql:latest
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./databases/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: pass
      PMA_PORT: 3306